import Foundation

func mkVoice(_ id: String, _ name: String, _ latin: String, _ group: Int,
             _ months: Int, _ hours: Int, _ habitats: Int, _ perch: Int, _ wet: Bool,
             carrier: Double, band: Double, rate20: Double, tempSlope: Double,
             pulse: Double, burst: Int, burstGap: Double, phraseGap: Double = 0,
             sweep: Double = 0, harm: Int = 1, attack: Double = 0.18, level: Double = 0.80,
             timbre: Int, shape: Int, note: String, tell: String) -> Voice {
    Voice(id: id, name: name, latin: latin, group: group, months: months, hours: hours,
          habitats: habitats, perch: perch, wet: wet, carrier: carrier, band: band,
          rate20: rate20, tempSlope: tempSlope, pulse: pulse, burst: burst,
          burstGap: burstGap, phraseGap: phraseGap, sweep: sweep, harm: harm,
          attack: attack, level: level, timbre: timbre, shape: shape, note: note, tell: tell)
}

extension Registry {
    static let block1: [Voice] = [
        mkVoice("peeper", "Spring Peeper", "Pseudacris crucifer", 0,
                Cal.mar | Cal.apr | Cal.may | Cal.jun, Cal.hours(17, 3),
                Ground.pond | Ground.meadow | Ground.marsh | Ground.bottom, Perch.lowVeg, true,
                carrier: 2900, band: 0.05, rate20: 1.05, tempSlope: 0.030,
                pulse: 0.15, burst: 1, burstGap: 0.80, sweep: 320, attack: 0.22, level: 0.92,
                timbre: Timbre.whistled, shape: Shape.singles,
                note: "A frog the size of a thumbnail, calling from a stem an inch above the water with its throat blown out to twice the size of its head. In a full chorus a thousand of them go at once and the sound is genuinely painful at the water's edge.",
                tell: "A clean rising whistle about once a second. Nothing else in early spring is that high and that pure."),
        mkVoice("woodfrog", "Wood Frog", "Lithobates sylvaticus", 0,
                Cal.mar | Cal.apr, Cal.hours(8, 23),
                Ground.hardwood | Ground.bottom | Ground.pond, Perch.water, true,
                carrier: 1100, band: 0.55, rate20: 9.0, tempSlope: 0.040,
                pulse: 0.045, burst: 4, burstGap: 0.55,
                timbre: Timbre.nasal, shape: Shape.chirps,
                note: "The first frog of the year, out on the ice-edge of a vernal pool while there is still snow in the hollows. The whole breeding season can be over in five days.",
                tell: "A short duck-like chuckle in a woodland pool, and the season is finished before the peepers get loud."),
        mkVoice("chorusfrog", "Upland Chorus Frog", "Pseudacris feriarum", 0,
                Cal.feb | Cal.mar | Cal.apr | Cal.may, Cal.hours(16, 2),
                Ground.meadow | Ground.pond | Ground.bottom, Perch.lowVeg, true,
                carrier: 2700, band: 0.22, rate20: 17.0, tempSlope: 0.055,
                pulse: 0.020, burst: 14, burstGap: 1.30, sweep: 240,
                timbre: Timbre.rasping, shape: Shape.phrase,
                note: "Calls from flooded grass with almost no water under it, often in a field that will be dry by June.",
                tell: "A thumb run up the teeth of a comb, rising as it goes, then a second and a half of nothing."),
        mkVoice("graytree", "Gray Treefrog", "Hyla versicolor", 0,
                Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 3),
                Ground.hardwood | Ground.pond | Ground.garden | Ground.bottom, Perch.tree, true,
                carrier: 1150, band: 0.30, rate20: 21.0, tempSlope: 0.052,
                pulse: 0.020, burst: 22, burstGap: 2.60, sweep: 0, harm: 2, level: 0.86,
                timbre: Timbre.liquid, shape: Shape.phrase,
                note: "A tetraploid, meaning it carries twice the usual set of chromosomes. Its diploid twin looks identical and lives in the same trees; the only way to separate the two in the field is by the speed of the trill.",
                tell: "A slow musical trill you can very nearly count, about a second long, from up in a tree."),
        mkVoice("copestree", "Cope's Gray Treefrog", "Hyla chrysoscelis", 0,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 3),
                Ground.hardwood | Ground.pond | Ground.barren | Ground.bottom, Perch.tree, true,
                carrier: 1180, band: 0.45, rate20: 42.0, tempSlope: 0.058,
                pulse: 0.012, burst: 34, burstGap: 2.30, sweep: 0, harm: 2, level: 0.86,
                timbre: Timbre.rasping, shape: Shape.phrase,
                note: "The diploid half of the gray treefrog pair. Identical in the hand, identical in colour, and separable in the field only by pulse rate, which is roughly twice as fast at the same temperature.",
                tell: "The same trill as the gray treefrog, but too fast to count and distinctly harsher."),
        mkVoice("greenfrog", "Green Frog", "Lithobates clamitans", 0,
                Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(17, 5),
                Ground.pond | Ground.marsh | Ground.bottom, Perch.water, true,
                carrier: 380, band: 0.28, rate20: 1.2, tempSlope: 0.020,
                pulse: 0.22, burst: 1, burstGap: 3.20, sweep: -60, harm: 3,
                timbre: Timbre.nasal, shape: Shape.singles,
                note: "Territorial rather than advertising: a male on a fixed patch of bank answering the male on the next patch, all summer.",
                tell: "One loose banjo string, usually alone. When it does give three in a row, each one is lower than the last."),
        mkVoice("bullfrog", "American Bullfrog", "Lithobates catesbeianus", 0,
                Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(18, 5),
                Ground.pond | Ground.marsh | Ground.bottom, Perch.water, true,
                carrier: 190, band: 0.20, rate20: 1.6, tempSlope: 0.018,
                pulse: 0.55, burst: 2, burstGap: 1.10, phraseGap: 6, sweep: 0, harm: 4, level: 0.95,
                timbre: Timbre.nasal, shape: Shape.phrase,
                note: "The largest frog on the continent and the deepest voice on the pond. The call carries because it is low, and low sound bends around cattails instead of being absorbed by them.",
                tell: "Two or three very long low notes with a sag in the middle of each. Nothing else is that far down."),
        mkVoice("leopardfrog", "Northern Leopard Frog", "Lithobates pipiens", 0,
                Cal.mar | Cal.apr | Cal.may, Cal.hours(18, 4),
                Ground.meadow | Ground.pond | Ground.marsh, Perch.water, true,
                carrier: 950, band: 0.62, rate20: 13.0, tempSlope: 0.042,
                pulse: 0.045, burst: 44, burstGap: 2.20,
                timbre: Timbre.noisy, shape: Shape.churr,
                note: "Calls from open water, often with the head barely breaking the surface, and very often from underneath it, which is why the snore sounds muffled.",
                tell: "A long wet snore, then two or three chuckles like a thumb dragged over a wet balloon.")
    ]

    static let block2: [Voice] = [
        mkVoice("pickerelfrog", "Pickerel Frog", "Lithobates palustris", 0,
                Cal.apr | Cal.may, Cal.hours(18, 4),
                Ground.bottom | Ground.pond | Ground.meadow, Perch.water, true,
                carrier: 740, band: 0.58, rate20: 11.0, tempSlope: 0.040,
                pulse: 0.050, burst: 18, burstGap: 3.40, level: 0.62,
                timbre: Timbre.noisy, shape: Shape.churr,
                note: "Skin secretions toxic enough to kill other frogs in the same bucket, which is why it is often the only frog in a cold clear stream.",
                tell: "A steady low snore with no chuckle on the end, and often coming from under the water."),
        mkVoice("amtoad", "American Toad", "Anaxyrus americanus", 0,
                Cal.mar | Cal.apr | Cal.may | Cal.jun, Cal.hours(17, 3),
                Ground.garden | Ground.meadow | Ground.pond | Ground.hardwood, Perch.water, true,
                carrier: 1950, band: 0.05, rate20: 34.0, tempSlope: 0.048,
                pulse: 0.012, burst: 500, burstGap: 4.00, level: 0.90,
                timbre: Timbre.pure, shape: Shape.trill,
                note: "One of the purest tones in the night: a single narrow band on the spectrogram with the pulses showing as a fine comb inside it. A male can hold the trill for thirty seconds.",
                tell: "A long high musical trill that does not stop to breathe. Count the pulses and it is about thirty-four a second on a mild night."),
        mkVoice("fowlertoad", "Fowler's Toad", "Anaxyrus fowleri", 0,
                Cal.may | Cal.jun | Cal.jul, Cal.hours(18, 2),
                Ground.barren | Ground.bottom | Ground.pond | Ground.garden, Perch.water, true,
                carrier: 1500, band: 0.78, rate20: 60.0, tempSlope: 0.045,
                pulse: 0.008, burst: 150, burstGap: 3.00,
                timbre: Timbre.noisy, shape: Shape.trill,
                note: "Overlaps completely with the American toad in range and habitat and hybridises with it, which produces individuals whose call is halfway between the two.",
                tell: "A nasal bleat like a sheep with a cold. There is nothing musical in it at all."),
        mkVoice("spadefoot", "Eastern Spadefoot", "Scaphiopus holbrookii", 0,
                Cal.mar | Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep, Cal.hours(19, 3),
                Ground.barren | Ground.wash | Ground.meadow, Perch.water, true,
                carrier: 480, band: 0.50, rate20: 0.8, tempSlope: 0.020,
                pulse: 0.50, burst: 1, burstGap: 1.60, sweep: -140, harm: 2,
                timbre: Timbre.nasal, shape: Shape.singles,
                note: "Spends most of its life a foot underground and comes up only for heavy warm rain. A population can go two years without calling at all, then fill a flooded field for a single night.",
                tell: "A low groan with a drop in it, heard only after a downpour and almost never two nights running."),
        mkVoice("cricketfrog", "Northern Cricket Frog", "Acris crepitans", 0,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(9, 2),
                Ground.pond | Ground.meadow | Ground.bottom, Perch.ground, true,
                carrier: 3600, band: 0.38, rate20: 6.0, tempSlope: 0.050,
                pulse: 0.008, burst: 22, burstGap: 2.20,
                timbre: Timbre.rasping, shape: Shape.clicks,
                note: "A frog that sounds exactly like an insect, which is how it gets its name and why it is passed over so often. It calls in full daylight as well as at night.",
                tell: "Two pebbles knocked together, slow to start and then running away with itself."),
        mkVoice("narrowmouth", "Eastern Narrow-mouthed Toad", "Gastrophryne carolinensis", 0,
                Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 3),
                Ground.meadow | Ground.bottom | Ground.barren, Perch.ground, true,
                carrier: 3000, band: 0.62, rate20: 90.0, tempSlope: 0.050,
                pulse: 0.006, burst: 190, burstGap: 4.00,
                timbre: Timbre.nasal, shape: Shape.trill,
                note: "Not a toad at all but a microhylid, with a fold of skin across the back of its head that it wipes forward over its eyes. It eats almost nothing but ants.",
                tell: "A bleating buzz with a tiny bleat in front of it, like a lamb through a kazoo."),
        mkVoice("carpenterfrog", "Carpenter Frog", "Lithobates virgatipes", 0,
                Cal.apr | Cal.may | Cal.jun | Cal.jul, Cal.hours(17, 4),
                Ground.barren | Ground.marsh | Ground.bottom, Perch.water, true,
                carrier: 1000, band: 0.55, rate20: 4.4, tempSlope: 0.035,
                pulse: 0.040, burst: 5, burstGap: 2.40,
                timbre: Timbre.rasping, shape: Shape.chirps,
                note: "Restricted to acid sphagnum water on the coastal plain, so hearing it at all tells you a great deal about where you are standing.",
                tell: "Four or five hammer blows on a plank, always the same rhythm, always the same number."),
        mkVoice("fieldcricket", "Fall Field Cricket", "Gryllus pennsylvanicus", 1,
                Cal.aug | Cal.sep | Cal.oct | Cal.nov, Cal.hours(15, 6),
                Ground.meadow | Ground.garden | Ground.barren | Ground.hardwood, Perch.ground, false,
                carrier: 4700, band: 0.10, rate20: 26.0, tempSlope: 0.055,
                pulse: 0.012, burst: 4, burstGap: 0.26, level: 0.82,
                timbre: Timbre.pure, shape: Shape.chirps,
                note: "Calls from a crack in the ground or under a board, with the wings held up over the back like a tent so the whole body works as a baffle.",
                tell: "Three or four hard chirps a second from ground level, and it audibly slows as the night cools.")
    ]

    static let block3: [Voice] = [
        mkVoice("snowytree", "Snowy Tree Cricket", "Oecanthus fultoni", 1,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(18, 5),
                Ground.garden | Ground.meadow | Ground.hardwood | Ground.bottom, Perch.lowVeg, false,
                carrier: 2600, band: 0.03, rate20: 60.0, tempSlope: 0.064,
                pulse: 0.008, burst: 8, burstGap: 0.332, level: 0.74,
                timbre: Timbre.pure, shape: Shape.chirps,
                note: "The thermometer cricket. Amos Dolbear published the relation in 1897, and the field version of it still works: count the chirps in thirteen seconds and add forty for degrees Fahrenheit.",
                tell: "A pure sweet chirp on one pitch, all the crickets in a hedge chirping in step with each other."),
        mkVoice("fourspot", "Four-spotted Tree Cricket", "Oecanthus quadripunctatus", 1,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(18, 5),
                Ground.meadow | Ground.garden | Ground.barren, Perch.lowVeg, false,
                carrier: 4000, band: 0.06, rate20: 55.0, tempSlope: 0.055,
                pulse: 0.010, burst: 0, burstGap: 0, level: 0.68,
                timbre: Timbre.pure, shape: Shape.trill,
                note: "Calls from weed stems in old fields, usually goldenrod. The trill runs unbroken for minutes, which is what separates it from its chirping relatives.",
                tell: "A continuous silvery trill on one note, higher than a snowy tree cricket and with no gaps."),
        mkVoice("narrowwing", "Narrow-winged Tree Cricket", "Oecanthus niveus", 1,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(19, 4),
                Ground.hardwood | Ground.garden | Ground.bottom, Perch.tree, false,
                carrier: 4200, band: 0.07, rate20: 45.0, tempSlope: 0.055,
                pulse: 0.010, burst: 6, burstGap: 0.10, level: 0.66,
                timbre: Timbre.pure, shape: Shape.chirps,
                note: "Calls from shrubs and small trees, often the same individual on the same branch for weeks.",
                tell: "A pulsed trill that is almost continuous, with a faint stutter you only hear when it is close."),
        mkVoice("allardground", "Allard's Ground Cricket", "Allonemobius allardi", 1,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(12, 6),
                Ground.meadow | Ground.garden | Ground.barren, Perch.ground, false,
                carrier: 7000, band: 0.10, rate20: 90.0, tempSlope: 0.050,
                pulse: 0.007, burst: 0, burstGap: 0, level: 0.55,
                timbre: Timbre.pure, shape: Shape.trill,
                note: "One of the small brown crickets that make the constant thin background of a late summer field. There are usually several hundred within earshot.",
                tell: "A high thin buzzy trill with no shape to it, so quiet that it reads as the background rather than a voice."),
        mkVoice("carolinaground", "Carolina Ground Cricket", "Eunemobius carolinus", 1,
                Cal.jun | Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(12, 6),
                Ground.hardwood | Ground.garden | Ground.bottom | Ground.meadow, Perch.ground, false,
                carrier: 6200, band: 0.16, rate20: 70.0, tempSlope: 0.050,
                pulse: 0.008, burst: 0, burstGap: 0, level: 0.52,
                timbre: Timbre.pure, shape: Shape.trill,
                note: "Lives in leaf litter and under stones and calls day and night from midsummer to the first hard frost.",
                tell: "A soft rolling buzz that swells and dies rather than stopping, and it comes from under your feet."),
        mkVoice("molecricket", "Northern Mole Cricket", "Neocurtilla hexadactyla", 1,
                Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 2),
                Ground.meadow | Ground.pond | Ground.bottom, Perch.burrow, true,
                carrier: 2000, band: 0.35, rate20: 55.0, tempSlope: 0.045,
                pulse: 0.010, burst: 0, burstGap: 0, level: 0.78,
                timbre: Timbre.rasping, shape: Shape.churr,
                note: "Digs a burrow shaped like a pair of horns opening at the surface and sings into the narrow end. The burrow is a genuine acoustic horn and it roughly doubles the sound the animal can radiate.",
                tell: "A low churr coming out of wet bare ground, with a boxy quality to it that gives away the burrow."),
        mkVoice("springfield", "Spring Field Cricket", "Gryllus veletis", 1,
                Cal.may | Cal.jun | Cal.jul, Cal.hours(15, 6),
                Ground.meadow | Ground.garden | Ground.barren, Perch.ground, false,
                carrier: 4800, band: 0.10, rate20: 27.0, tempSlope: 0.055,
                pulse: 0.012, burst: 4, burstGap: 0.24, level: 0.80,
                timbre: Timbre.pure, shape: Shape.chirps,
                note: "Overwinters as a well grown nymph rather than as an egg, which is why it is singing in May while its autumn counterpart is still underground.",
                tell: "Identical in sound to the fall field cricket. The date is the identification: this one sings before midsummer."),
        mkVoice("truekatydid", "Common True Katydid", "Pterophylla camellifolia", 2,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(20, 4),
                Ground.hardwood | Ground.garden | Ground.bottom, Perch.tree, false,
                carrier: 4200, band: 0.72, rate20: 11.0, tempSlope: 0.045,
                pulse: 0.070, burst: 3, burstGap: 0.85, level: 0.95,
                timbre: Timbre.rasping, shape: Shape.chirps,
                note: "Spends its whole life in the canopy and is almost never seen. Neighbouring males alternate rather than overlap, so a wood full of them beats like a slow engine.",
                tell: "Two, three or four harsh rasps in the rhythm of its own name, from high in a hardwood, over and over until dawn.")
    ]

    static let block4: [Voice] = [
        mkVoice("anglewing", "Greater Anglewing", "Microcentrum rhombifolium", 2,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(20, 4),
                Ground.hardwood | Ground.garden | Ground.bottom, Perch.tree, false,
                carrier: 9000, band: 0.82, rate20: 30.0, tempSlope: 0.045,
                pulse: 0.010, burst: 1, burstGap: 2.40, level: 0.70,
                timbre: Timbre.rasping, shape: Shape.singles,
                note: "A big pale green katydid shaped exactly like a leaf, down to the veins. The male also drums on a branch with his feet, which the female answers with a tick.",
                tell: "A single dry tsip every two or three seconds, high enough that it seems to come from nowhere in particular."),
        mkVoice("oblongwing", "Oblong-winged Katydid", "Amblycorypha oblongifolia", 2,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(20, 3),
                Ground.meadow | Ground.bottom | Ground.hardwood, Perch.lowVeg, false,
                carrier: 8000, band: 0.76, rate20: 26.0, tempSlope: 0.045,
                pulse: 0.014, burst: 2, burstGap: 3.50, level: 0.66,
                timbre: Timbre.rasping, shape: Shape.chirps,
                note: "Usually green, but a pink form turns up regularly and is not a separate species; it is a single recessive gene.",
                tell: "A raspy double tzeet with several seconds of silence between, from shrubs rather than from the canopy."),
        mkVoice("roundconehead", "Round-tipped Conehead", "Neoconocephalus retusus", 2,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(19, 4),
                Ground.meadow | Ground.barren | Ground.garden, Perch.lowVeg, false,
                carrier: 12500, band: 0.60, rate20: 160.0, tempSlope: 0.050,
                pulse: 0.004, burst: 0, burstGap: 0, level: 0.72,
                timbre: Timbre.rasping, shape: Shape.trill,
                note: "A slim green insect with a pointed cone on the front of its head, calling from tall grass. Many people over forty cannot hear it at all.",
                tell: "A continuous high buzz with no rhythm, right at the top of the range. If it vanishes when you cup your ears forward you are at your own hearing limit."),
        mkVoice("swordconehead", "Sword-bearing Conehead", "Neoconocephalus ensiger", 2,
                Cal.jul | Cal.aug | Cal.sep | Cal.oct, Cal.hours(19, 4),
                Ground.meadow | Ground.bottom | Ground.marsh, Perch.lowVeg, false,
                carrier: 11000, band: 0.66, rate20: 12.0, tempSlope: 0.062,
                pulse: 0.030, burst: 0, burstGap: 0, level: 0.74,
                timbre: Timbre.rasping, shape: Shape.churr,
                note: "The female carries a long straight ovipositor like a sword, which is where the name comes from. The lisping rate tracks temperature closely enough to be useful.",
                tell: "A steady tsip-tsip-tsip at about a dozen a second, like a very small steam engine in the grass."),
        mkVoice("robustconehead", "Robust Conehead", "Neoconocephalus robustus", 2,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(19, 3),
                Ground.marsh | Ground.meadow | Ground.bottom, Perch.lowVeg, true,
                carrier: 10000, band: 0.55, rate20: 200.0, tempSlope: 0.050,
                pulse: 0.003, burst: 0, burstGap: 0, level: 1.00,
                timbre: Timbre.rasping, shape: Shape.trill,
                note: "One of the loudest insects on the continent. Standing beside a calling male is genuinely uncomfortable, and a marsh full of them is a solid wall you cannot hear through.",
                tell: "An unbroken buzz so loud and so even that it stops sounding like an animal and starts sounding like machinery."),
        mkVoice("meadowkatydid", "Black-legged Meadow Katydid", "Orchelimum nigripes", 2,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(10, 2),
                Ground.marsh | Ground.meadow | Ground.pond, Perch.lowVeg, true,
                carrier: 9500, band: 0.70, rate20: 8.0, tempSlope: 0.048,
                pulse: 0.030, burst: 6, burstGap: 1.40, level: 0.68,
                timbre: Timbre.rasping, shape: Shape.chirps,
                note: "Calls from cattail and sedge in full sun as well as after dark, so it is one of the easier singers to actually find and look at.",
                tell: "A run of dry ticks and then a short buzz, over and over, from waist height in wet grass."),
        mkVoice("scissorgrinder", "Scissor-grinder Cicada", "Neotibicen pruinosus", 3,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(17, 21),
                Ground.hardwood | Ground.garden | Ground.bottom, Perch.tree, false,
                carrier: 5000, band: 0.45, rate20: 3.5, tempSlope: 0.030,
                pulse: 0.220, burst: 0, burstGap: 0, level: 0.90,
                timbre: Timbre.rasping, shape: Shape.churr,
                note: "Not a stridulator: a pair of ribbed membranes called tymbals on the sides of the abdomen buckle in and out, and the hollow body amplifies it.",
                tell: "A pulsing eee-oo eee-oo that swells and fades several times a second, always in the last hour of light."),
        mkVoice("dogday", "Dog-day Cicada", "Neotibicen canicularis", 3,
                Cal.jul | Cal.aug | Cal.sep, Cal.hours(9, 20),
                Ground.hardwood | Ground.garden | Ground.barren, Perch.tree, false,
                carrier: 8000, band: 0.50, rate20: 0.25, tempSlope: 0.020,
                pulse: 3.00, burst: 1, burstGap: 2.00, sweep: 900, level: 0.88,
                timbre: Timbre.rasping, shape: Shape.singles,
                note: "Annual, despite the underground nymph taking two to five years. Overlapping broods mean some emerge every summer.",
                tell: "A long whine like a circular saw that rises, holds, and dies away over four or five seconds.")
    ]
}
