import Foundation

extension Registry {
    static let block5: [Voice] = [
        mkVoice("periodical", "Periodical Cicada", "Magicicada septendecim", 3,
                Cal.may | Cal.jun, Cal.hours(8, 19),
                Ground.hardwood | Ground.bottom | Ground.garden, Perch.tree, false,
                carrier: 1350, band: 0.35, rate20: 0.35, tempSlope: 0.020,
                pulse: 2.40, burst: 1, burstGap: 1.60, sweep: -420, level: 0.92,
                timbre: Timbre.nasal, shape: Shape.phrase,
                note: "Seventeen years underground on tree root sap, then six weeks above it. Emergence is synchronised across a whole brood, so a wood can go from silent to a hundred thousand singing insects in three days.",
                tell: "A long droning phrase that sags in pitch at the end, in numbers, and only in a year when the brood is up."),
        mkVoice("greathorned", "Great Horned Owl", "Bubo virginianus", 4,
                Cal.allYear, Cal.hours(17, 6),
                Ground.hardwood | Ground.garden | Ground.bottom | Ground.barren | Ground.wash, Perch.tree, false,
                carrier: 300, band: 0.06, rate20: 2.4, tempSlope: 0,
                pulse: 0.42, burst: 4, burstGap: 0.35, phraseGap: 9, sweep: 0, harm: 3, level: 0.95,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "Nests in January and February, in snow, on a stolen hawk's nest. The pair duet, and the female is the larger bird but has the higher voice, which is the reverse of what people expect.",
                tell: "Four or five deep hoots in a stuttering rhythm, low enough that you feel them as much as hear them."),
        mkVoice("barred", "Barred Owl", "Strix varia", 4,
                Cal.allYear, Cal.hours(17, 7),
                Ground.hardwood | Ground.bottom | Ground.marsh, Perch.tree, false,
                carrier: 480, band: 0.08, rate20: 3.4, tempSlope: 0,
                pulse: 0.26, burst: 8, burstGap: 0.14, phraseGap: 7, sweep: -60, harm: 2, level: 0.92,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "Needs old wet woodland with big hollow trees. It is also the noisiest owl there is: a pair working each other up produces caterwauling that people report as someone being attacked.",
                tell: "Eight notes in two groups of four, with the very last one dragged downward and drawn out."),
        mkVoice("screech", "Eastern Screech-Owl", "Megascops asio", 4,
                Cal.allYear, Cal.hours(18, 6),
                Ground.garden | Ground.hardwood | Ground.bottom, Perch.tree, false,
                carrier: 900, band: 0.10, rate20: 22.0, tempSlope: 0,
                pulse: 0.045, burst: 34, burstGap: 5.00, sweep: -380, level: 0.72,
                timbre: Timbre.whistled, shape: Shape.churr,
                note: "The commonest owl in suburbs, living in nest boxes and hollow street trees, and almost never seen because it is the size of a pint glass.",
                tell: "A horse's whinny falling down the scale, or else a long even trill held on one pitch."),
        mkVoice("sawwhet", "Northern Saw-whet Owl", "Aegolius acadicus", 4,
                Cal.feb | Cal.mar | Cal.apr | Cal.may, Cal.hours(19, 5),
                Ground.hardwood | Ground.barren | Ground.bottom, Perch.tree, false,
                carrier: 1100, band: 0.04, rate20: 2.0, tempSlope: 0,
                pulse: 0.11, burst: 0, burstGap: 0, level: 0.70,
                timbre: Timbre.whistled, shape: Shape.trill,
                note: "Named for a call that reminded somebody of a saw being sharpened, which is not the call it is famous for. It can keep the tooting up for well over an hour without a break.",
                tell: "A toot exactly twice a second, on and on, like a truck reversing somewhere in the woods."),
        mkVoice("barnowl", "Barn Owl", "Tyto alba", 4,
                Cal.allYear, Cal.hours(19, 5),
                Ground.meadow | Ground.garden | Ground.marsh, Perch.air, false,
                carrier: 3200, band: 0.90, rate20: 0.6, tempSlope: 0,
                pulse: 1.30, burst: 1, burstGap: 4.50, sweep: -600, level: 0.82,
                timbre: Timbre.noisy, shape: Shape.singles,
                note: "Hunts entirely by ear, with one ear opening set higher than the other so that a sound arriving from below hits them at different times. It can take a mouse in total darkness.",
                tell: "A tearing shriek with no music in it whatsoever, usually from a bird already going past."),
        mkVoice("longeared", "Long-eared Owl", "Asio otus", 4,
                Cal.feb | Cal.mar | Cal.apr | Cal.may, Cal.hours(19, 5),
                Ground.barren | Ground.hardwood | Ground.meadow, Perch.tree, false,
                carrier: 380, band: 0.05, rate20: 0.34, tempSlope: 0,
                pulse: 0.30, burst: 0, burstGap: 0, sweep: 0, harm: 2, level: 0.60,
                timbre: Timbre.whistled, shape: Shape.trill,
                note: "Roosts communally in dense conifers in winter, sometimes a dozen birds in one tree, and is missed constantly because it sits bolt upright against a trunk.",
                tell: "One soft hoo every three seconds, spaced like a metronome, as if somebody were blowing across a bottle."),
        mkVoice("shorteared", "Short-eared Owl", "Asio flammeus", 4,
                Cal.mar | Cal.apr | Cal.may | Cal.nov | Cal.dec | Cal.jan, Cal.hours(16, 21),
                Ground.meadow | Ground.marsh, Perch.air, false,
                carrier: 420, band: 0.12, rate20: 4.5, tempSlope: 0,
                pulse: 0.14, burst: 14, burstGap: 3.00, level: 0.62,
                timbre: Timbre.whistled, shape: Shape.chirps,
                note: "Hunts in the open in daylight as well as at dusk, quartering low over grassland like a moth. The male display flight includes a wing-clap under the body.",
                tell: "A soft rapid poo-poo-poo over open ground, often with a raspy bark somewhere after it.")
    ]

    static let block6: [Voice] = [
        mkVoice("whippoorwill", "Eastern Whip-poor-will", "Antrostomus vociferus", 5,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 5),
                Ground.hardwood | Ground.barren | Ground.bottom, Perch.ground, false,
                carrier: 1800, band: 0.15, rate20: 3.4, tempSlope: 0,
                pulse: 0.16, burst: 3, burstGap: 0.55, sweep: 520, level: 0.90,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "Times its breeding to the moon so that the chicks hatch when there is enough moonlight to hunt moths by. Counts of over a thousand calls without a pause are on record.",
                tell: "Three syllables with the last one thrown up and out, repeated until you genuinely lose count."),
        mkVoice("chuckwills", "Chuck-will's-widow", "Antrostomus carolinensis", 5,
                Cal.apr | Cal.may | Cal.jun | Cal.jul, Cal.hours(19, 5),
                Ground.barren | Ground.bottom | Ground.hardwood, Perch.ground, false,
                carrier: 1250, band: 0.18, rate20: 3.0, tempSlope: 0,
                pulse: 0.18, burst: 4, burstGap: 0.70, sweep: 300, level: 0.88,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "Bigger than a whip-poor-will and with a mouth wide enough to swallow small birds whole, which it has been recorded doing.",
                tell: "Four syllables instead of three, lower and lazier, with the first one almost swallowed."),
        mkVoice("nighthawk", "Common Nighthawk", "Chordeiles minor", 5,
                Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep, Cal.hours(18, 22),
                Ground.garden | Ground.meadow | Ground.barren | Ground.wash, Perch.air, false,
                carrier: 2200, band: 0.55, rate20: 0.36, tempSlope: 0,
                pulse: 0.16, burst: 1, burstGap: 2.60, level: 0.76,
                timbre: Timbre.nasal, shape: Shape.singles,
                note: "Nests on flat gravel roofs in towns. The boom at the bottom of the display dive is not a voice at all: it is air through the primary feathers.",
                tell: "A flat nasal peent from high overhead, and then a hollow boom as the bird pulls out of a dive."),
        mkVoice("poorwill", "Common Poorwill", "Phalaenoptilus nuttallii", 5,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(19, 5),
                Ground.wash | Ground.barren, Perch.ground, false,
                carrier: 1200, band: 0.14, rate20: 2.4, tempSlope: 0,
                pulse: 0.20, burst: 2, burstGap: 1.30, sweep: 260, level: 0.72,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "The only bird known to hibernate. It goes torpid in a rock crevice for weeks at a time, with its body temperature down near five degrees.",
                tell: "Two soft notes from a dry hillside, the second one rising, with a faint third note only audible close up."),
        mkVoice("woodcock", "American Woodcock", "Scolopax minor", 6,
                Cal.feb | Cal.mar | Cal.apr | Cal.may, Cal.hours(18, 20) | Cal.hours(4, 6),
                Ground.meadow | Ground.bottom | Ground.hardwood, Perch.ground, true,
                carrier: 1600, band: 0.62, rate20: 0.45, tempSlope: 0,
                pulse: 0.22, burst: 1, burstGap: 2.00, level: 0.74,
                timbre: Timbre.nasal, shape: Shape.singles,
                note: "The display is one of the set pieces of the spring night: peents from bare ground, then a spiral climb three hundred feet up on whistling wings, then a zigzag fall with a chirping twitter all the way down.",
                tell: "A buzzing nasal peent from open ground every two seconds, and then the bird goes up and you hear its wings instead."),
        mkVoice("virginiarail", "Virginia Rail", "Rallus limicola", 6,
                Cal.apr | Cal.may | Cal.jun | Cal.jul, Cal.hours(18, 6),
                Ground.marsh | Ground.pond | Ground.bottom, Perch.ground, true,
                carrier: 1400, band: 0.50, rate20: 5.5, tempSlope: 0,
                pulse: 0.09, burst: 3, burstGap: 0.50, level: 0.66,
                timbre: Timbre.nasal, shape: Shape.chirps,
                note: "Narrow enough front to back to walk between cattail stems without moving them, with flexible vertebrae to help. It is heard a hundred times for every time it is seen.",
                tell: "A hard kid-kid-kidick from inside dense reeds, with the last note doubled."),
        mkVoice("sora", "Sora", "Porzana carolina", 6,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug, Cal.hours(17, 7),
                Ground.marsh | Ground.pond, Perch.ground, true,
                carrier: 1900, band: 0.20, rate20: 12.0, tempSlope: 0,
                pulse: 0.06, burst: 22, burstGap: 4.00, sweep: -760, level: 0.70,
                timbre: Timbre.whistled, shape: Shape.churr,
                note: "The commonest rail in North America and still almost never seen. It also gives a rising two-note whistle that sounds like a question.",
                tell: "A descending whinny that starts high and tumbles down and slows, all from one point in the reeds."),
        mkVoice("bittern", "American Bittern", "Botaurus lentiginosus", 6,
                Cal.apr | Cal.may | Cal.jun, Cal.hours(17, 8),
                Ground.marsh | Ground.pond, Perch.ground, true,
                carrier: 200, band: 0.38, rate20: 1.6, tempSlope: 0,
                pulse: 0.34, burst: 3, burstGap: 2.40, sweep: 0, harm: 3, level: 0.86,
                timbre: Timbre.nasal, shape: Shape.phrase,
                note: "Gulps air into its oesophagus and then forces it out, with the whole body convulsing. The sound has been compared to a stake being driven and to a very old pump, and it carries half a mile.",
                tell: "Three gulping notes from deep in the cattails, lower than anything else out there and impossible to place.")
    ]

    static let block7: [Voice] = [
        mkVoice("nightheron", "Black-crowned Night-Heron", "Nycticorax nycticorax", 6,
                Cal.mar | Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep, Cal.hours(18, 5),
                Ground.marsh | Ground.pond | Ground.bottom | Ground.garden, Perch.air, true,
                carrier: 700, band: 0.62, rate20: 0.30, tempSlope: 0,
                pulse: 0.16, burst: 1, burstGap: 5.00, level: 0.78,
                timbre: Timbre.noisy, shape: Shape.singles,
                note: "Roosts in a colony by day and disperses at dusk to fish, which is when the flat bark comes out of the sky over a suburb that has no idea it is there.",
                tell: "A single flat quok from directly overhead, once, and then it is gone."),
        mkVoice("loon", "Common Loon", "Gavia immer", 6,
                Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep, Cal.hours(19, 6),
                Ground.pond | Ground.bottom, Perch.water, true,
                carrier: 700, band: 0.06, rate20: 0.55, tempSlope: 0,
                pulse: 1.50, burst: 2, burstGap: 1.20, sweep: 280, harm: 2, level: 0.90,
                timbre: Timbre.whistled, shape: Shape.phrase,
                note: "Four distinct calls: the wail for contact across water, the tremolo for alarm, the yodel given only by males and unique to the individual, and a soft hoot within the family.",
                tell: "A long clear wail that rises and holds, with an echo off the far shore a beat behind it."),
        mkVoice("swainsons", "Swainson's Thrush", "Catharus ustulatus", 6,
                Cal.apr | Cal.may | Cal.sep | Cal.oct, Cal.hours(21, 5),
                Ground.anywhere, Perch.air, false,
                carrier: 3200, band: 0.10, rate20: 0.14, tempSlope: 0,
                pulse: 0.09, burst: 1, burstGap: 7.00, sweep: 640, level: 0.48,
                timbre: Timbre.whistled, shape: Shape.singles,
                note: "Migrates at night at two to five thousand feet and calls as it goes, so on a good night in May you can stand in a city street and count birds passing over in the dark.",
                tell: "One short rising note out of an empty sky, then a minute of nothing, then another from further along."),
        mkVoice("killdeer", "Killdeer", "Charadrius vociferus", 6,
                Cal.allYear, Cal.hours(18, 6),
                Ground.meadow | Ground.garden | Ground.wash | Ground.bottom, Perch.air, false,
                carrier: 2600, band: 0.25, rate20: 3.2, tempSlope: 0,
                pulse: 0.14, burst: 2, burstGap: 1.10, sweep: 420, level: 0.76,
                timbre: Timbre.whistled, shape: Shape.chirps,
                note: "A shorebird that nests on gravel car parks and flat roofs, and calls all night in the breeding season, which is why it is on this list at all.",
                tell: "A strident two-note kill-deer over a car park at two in the morning, rising and slightly hysterical."),
        mkVoice("redfox", "Red Fox", "Vulpes vulpes", 7,
                Cal.dec | Cal.jan | Cal.feb | Cal.mar, Cal.hours(18, 5),
                Ground.garden | Ground.meadow | Ground.hardwood | Ground.barren, Perch.ground, false,
                carrier: 900, band: 0.58, rate20: 0.40, tempSlope: 0,
                pulse: 0.48, burst: 1, burstGap: 2.40, sweep: -200, harm: 2, level: 0.88,
                timbre: Timbre.noisy, shape: Shape.singles,
                note: "The scream belongs to the winter mating season and is given by both sexes. It is the single most reported wildlife sound in suburbs, almost always as a person or a cat in trouble.",
                tell: "A hoarse scream that sounds far too human. Two or three of them, then complete silence."),
        mkVoice("grayfox", "Gray Fox", "Urocyon cinereoargenteus", 7,
                Cal.dec | Cal.jan | Cal.feb | Cal.mar, Cal.hours(19, 5),
                Ground.hardwood | Ground.barren | Ground.bottom | Ground.wash, Perch.ground, false,
                carrier: 700, band: 0.68, rate20: 2.4, tempSlope: 0,
                pulse: 0.16, burst: 5, burstGap: 1.60, level: 0.72,
                timbre: Timbre.noisy, shape: Shape.chirps,
                note: "The only canid in North America that climbs trees, with hooked claws and rotating forearms, so its bark can come from twenty feet up.",
                tell: "A rasping bark repeated four or five times on the same note, drier and rougher than a dog."),
        mkVoice("coyote", "Coyote", "Canis latrans", 7,
                Cal.allYear, Cal.hours(18, 6),
                Ground.meadow | Ground.wash | Ground.barren | Ground.garden | Ground.bottom, Perch.ground, false,
                carrier: 750, band: 0.30, rate20: 3.6, tempSlope: 0,
                pulse: 0.18, burst: 8, burstGap: 1.40, sweep: 340, harm: 2, level: 0.92,
                timbre: Timbre.nasal, shape: Shape.phrase,
                note: "Two animals answering each other produce so much frequency modulation that people reliably hear six or eight. The effect has a name in the literature: the beau geste.",
                tell: "A rising howl that breaks into yipping. It sounds like a crowd and it is usually a pair."),
        mkVoice("flyingsquirrel", "Southern Flying Squirrel", "Glaucomys volans", 7,
                Cal.allYear, Cal.hours(19, 5),
                Ground.hardwood | Ground.garden | Ground.bottom, Perch.tree, false,
                carrier: 11000, band: 0.30, rate20: 7.0, tempSlope: 0,
                pulse: 0.045, burst: 3, burstGap: 1.50, sweep: -400, level: 0.52,
                timbre: Timbre.whistled, shape: Shape.chirps,
                note: "Far commoner than the grey squirrel in mature oak woodland and almost never seen, because it is out only between full dark and first light.",
                tell: "A thin high chirp from an oak trunk, high enough that some people beside you will hear nothing.")
    ]

    static let block8: [Voice] = [
        mkVoice("bigbrownbat", "Big Brown Bat", "Eptesicus fuscus", 7,
                Cal.mar | Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep | Cal.oct,
                Cal.hours(19, 4),
                Ground.garden | Ground.meadow | Ground.pond | Ground.hardwood, Perch.air, false,
                carrier: 13000, band: 0.40, rate20: 9.0, tempSlope: 0,
                pulse: 0.012, burst: 6, burstGap: 1.10, sweep: -3000, level: 0.44,
                timbre: Timbre.rasping, shape: Shape.clicks,
                note: "The hunting calls proper run from twenty to fifty kilohertz and no human hears them. What you can sometimes catch are the social calls, which sit low enough to be at the edge of a young ear.",
                tell: "Sharp clicks right at the top of your hearing, from something moving fast. If you are over forty you may get nothing at all."),
        mkVoice("raccoon", "Raccoon", "Procyon lotor", 7,
                Cal.allYear, Cal.hours(19, 5),
                Ground.garden | Ground.bottom | Ground.hardwood | Ground.marsh, Perch.ground, false,
                carrier: 1400, band: 0.62, rate20: 14.0, tempSlope: 0,
                pulse: 0.045, burst: 20, burstGap: 1.20, level: 0.70,
                timbre: Timbre.noisy, shape: Shape.churr,
                note: "Has something like fifty distinguishable vocalisations. Two of them arguing over a bin sounds like a serious fight and almost never is.",
                tell: "A churring, chittering argument at ground level with a lot of different pitches in it at once."),
        mkVoice("freighttrain", "Distant Freight Train", "Not an animal", 8,
                Cal.allYear, Cal.hours(0, 23), Ground.anywhere, Perch.ground, false,
                carrier: 90, band: 0.55, rate20: 0.16, tempSlope: 0,
                pulse: 5.00, burst: 1, burstGap: 2.00, sweep: -30, harm: 4, level: 0.66,
                timbre: Timbre.noisy, shape: Shape.singles,
                note: "Low frequencies travel further and bend around obstacles, and on a still night with an inversion layer overhead they can reflect back down. A train ten miles off can sound like one two fields away.",
                tell: "It never repeats on a fixed rhythm. It gets louder for a minute or two, and then it goes away and does not come back."),
        mkVoice("generator", "Portable Generator", "Not an animal", 8,
                Cal.allYear, Cal.hours(0, 23), Ground.garden | Ground.meadow | Ground.bottom,
                Perch.ground, false,
                carrier: 120, band: 0.16, rate20: 0.0, tempSlope: 0,
                pulse: 60.0, burst: 0, burstGap: 0, sweep: 0, harm: 4, level: 0.58,
                timbre: Timbre.nasal, shape: Shape.trill,
                note: "Sits on a single frequency and its harmonics with almost no drift, which no animal manages. On a spectrogram it is a stack of perfectly straight horizontal lines.",
                tell: "Perfectly steady, perfectly unvarying, and it never stops to breathe."),
        mkVoice("sprinkler", "Lawn Sprinkler", "Not an animal", 8,
                Cal.apr | Cal.may | Cal.jun | Cal.jul | Cal.aug | Cal.sep,
                Cal.hours(4, 8) | Cal.hours(19, 23), Ground.garden, Perch.ground, false,
                carrier: 2500, band: 0.88, rate20: 7.0, tempSlope: 0,
                pulse: 0.020, burst: 9, burstGap: 1.80, level: 0.62,
                timbre: Timbre.noisy, shape: Shape.clicks,
                note: "The impulse head ticks as the arm swings out and hisses on the return, which produces a rhythm that people file as an insect until they think about how exact it is.",
                tell: "The rhythm is mechanical to the millisecond, and it runs on a timer rather than on the weather."),
        mkVoice("squeakygate", "Squeaky Gate Hinge", "Not an animal", 8,
                Cal.allYear, Cal.hours(0, 23), Ground.garden | Ground.meadow,
                Perch.ground, false,
                carrier: 1100, band: 0.28, rate20: 0.25, tempSlope: 0,
                pulse: 0.80, burst: 1, burstGap: 5.00, sweep: 760, level: 0.56,
                timbre: Timbre.whistled, shape: Shape.singles,
                note: "Stick-slip friction on a dry pin produces a rising tone with a slightly ragged edge, which is very close indeed to a screech-owl's whinny.",
                tell: "It answers to a person and not to another gate. Wait for a second one somewhere else, and it never comes."),
        mkVoice("tinnitus", "Tinnitus", "Not an animal", 8,
                Cal.allYear, Cal.hours(0, 23), Ground.anywhere, Perch.air, false,
                carrier: 8000, band: 0.00, rate20: 0.0, tempSlope: 0,
                pulse: 60.0, burst: 0, burstGap: 0, level: 0.30,
                timbre: Timbre.pure, shape: Shape.trill,
                note: "A steady high tone generated inside the auditory system. It is extremely common, it gets more noticeable the quieter the surroundings, and a quiet field at two in the morning is about as quiet as surroundings get.",
                tell: "It does not get louder when you turn your head toward it, and it follows you indoors.")
    ]
}
